"""Loading and metering the served model (spec 8.2 / 8.4).

Two responsibilities, both deliberately small:

- `load_model()` puts Qwen2.5-1.5B-Instruct on the L4 at fp16 (~3 GB, leaving >20 GB
  for verifier subprocesses) with TF32 enabled, so the eager baseline the demo is
  measured against is the honest one (KernelBench-Verified).
- `TokenMeter` wraps `generate` and is the only thing that counts tokens. `/stats`
  reads it, the Streamlit dashboard polls it, and the demo's before/after number comes
  out of it — so it also records WHEN a kernel was swapped in, and whose kernel is
  currently live.

Critical: the model is never `torch.compile`d. Compiling bakes the current `forward`
into the graph, and a later monkey-patch silently no-ops (spec 8.3, gotcha 1).
"""

from __future__ import annotations

import threading
import time
from collections import deque
from typing import Any

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

from kernelsmith.config import SERVED_MODEL

#: Rolling window over recent /generate calls. Short enough that a swap shows up in
#: the dashboard within a couple of requests, long enough to survive one short prompt.
TOKENS_PER_SEC_WINDOW = 8

#: Tokens generated by the warmup pass. The first generate pays for CUDA context
#: setup and kernel autotuning; folding that into the rolling average would make every
#: later kernel look good by comparison.
WARMUP_TOKENS = 8


def load_model() -> tuple[Any, Any]:
    """Load Qwen2.5-1.5B-Instruct on the GPU in eval mode.

    Returns:
        (model, tokenizer). The model is fp16 on cuda, in eval mode, and NOT compiled.
    """
    torch.set_float32_matmul_precision("high")  # TF32 baseline (KernelBench-Verified)

    tokenizer = AutoTokenizer.from_pretrained(SERVED_MODEL)
    model = AutoModelForCausalLM.from_pretrained(
        SERVED_MODEL,
        torch_dtype=torch.float16,
        device_map="cuda",
    )
    model.eval()
    # No torch.compile here, on purpose. See the module docstring.
    return model, tokenizer


class TokenMeter:
    """Counts generated tokens and tracks which kernel is live.

    Thread-safe: FastAPI runs `generate` in a worker thread while `/stats` is served
    from the event loop, so both sides touch the counters concurrently.
    """

    def __init__(self, model: Any, tokenizer: Any, window: int = TOKENS_PER_SEC_WINDOW):
        self.model = model
        self.tokenizer = tokenizer
        self.total_tokens_generated = 0
        self.last_swap_ts: float | None = None
        self.active_kernel = "none"
        self._window: deque[tuple[int, float]] = deque(maxlen=window)
        self._lock = threading.Lock()

    # ----------------------------------------------------------------- metering

    @property
    def rolling_tokens_per_sec(self) -> float:
        """Tokens/s over the recent window, or 0.0 before anything was generated."""
        with self._lock:
            samples = list(self._window)
        if not samples:
            return 0.0
        seconds = sum(s for _, s in samples)
        return sum(t for t, _ in samples) / seconds if seconds > 0 else 0.0

    def record(self, tokens: int, seconds: float) -> None:
        """Fold one completed generation into the counters."""
        with self._lock:
            self.total_tokens_generated += int(tokens)
            if tokens > 0 and seconds > 0:
                self._window.append((int(tokens), float(seconds)))

    def record_swap(self, kernel_name: str) -> None:
        """Mark a kernel as live and start the rolling average over.

        The window is cleared because the point of `/stats` after a swap is the NEW
        kernel's throughput; averaging across the swap would blur exactly the number
        the demo is claiming.
        """
        with self._lock:
            self.active_kernel = kernel_name
            self.last_swap_ts = time.time()
            self._window.clear()

    def record_rollback(self) -> None:
        """Mark the model as back on its original forwards."""
        with self._lock:
            self.active_kernel = "none"
            self.last_swap_ts = time.time()
            self._window.clear()

    def stats(self) -> dict[str, Any]:
        """The `/stats` payload (spec 8.1)."""
        return {
            "tokens_per_s": self.rolling_tokens_per_sec,
            "tokens_total": self.total_tokens_generated,
            "active_kernel": self.active_kernel,
            "last_swap_ts": self.last_swap_ts,
        }

    # --------------------------------------------------------------- generation

    def generate(self, prompt: str, max_tokens: int = 128, temperature: float = 0.7) -> dict:
        """Generate a completion and meter it.

        Returns:
            {"text": str, "tokens": int, "time_ms": float} — `tokens` counts only the
            newly generated tokens, never the prompt.
        """
        inputs = self._encode(prompt)
        prompt_len = int(inputs["input_ids"].shape[-1])
        do_sample = temperature > 0

        start = time.perf_counter()
        with torch.inference_mode():
            output = self.model.generate(
                **inputs,
                max_new_tokens=max_tokens,
                do_sample=do_sample,
                # Passing a temperature with do_sample=False makes transformers warn
                # about an ignored generation flag; None keeps greedy decoding clean.
                temperature=temperature if do_sample else None,
                pad_token_id=self._pad_token_id(),
            )
        _synchronize()
        elapsed = time.perf_counter() - start

        new_ids = output[0][prompt_len:]
        tokens = int(new_ids.numel())
        self.record(tokens, elapsed)
        return {
            "text": self.tokenizer.decode(new_ids, skip_special_tokens=True),
            "tokens": tokens,
            "time_ms": elapsed * 1000.0,
        }

    def warmup(self, prompt: str = "Hello", tokens: int = WARMUP_TOKENS) -> None:
        """Run one short generation and discard its measurement."""
        before_total = self.total_tokens_generated
        self.generate(prompt, max_tokens=tokens, temperature=0.0)
        with self._lock:
            self.total_tokens_generated = before_total
            self._window.clear()

    def _encode(self, prompt: str) -> dict[str, Any]:
        """Apply the chat template when the tokenizer has one, else encode raw."""
        apply_chat_template = getattr(self.tokenizer, "apply_chat_template", None)
        if apply_chat_template is not None and getattr(self.tokenizer, "chat_template", None):
            encoded = apply_chat_template(
                [{"role": "user", "content": prompt}],
                add_generation_prompt=True,
                return_tensors="pt",
                return_dict=True,
            )
        else:
            encoded = self.tokenizer(prompt, return_tensors="pt")
        device = getattr(self.model, "device", None)
        return {
            key: (value.to(device) if device is not None and hasattr(value, "to") else value)
            for key, value in dict(encoded).items()
        }

    def _pad_token_id(self) -> Any:
        return getattr(self.tokenizer, "pad_token_id", None) or getattr(
            self.tokenizer, "eos_token_id", None
        )


def _synchronize() -> None:
    """Wait for the GPU before stopping the clock; generate() is async on device."""
    if torch.cuda.is_available():
        torch.cuda.synchronize()
